apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-usage-rate
spec:
  metrics:
    - name: cpu-usage-rate
      initialDelay: 2m
      successCondition: result < 2
      provider:
        prometheus:
          address: http://kube-prometheus-stack-1760-prometheus.prometheus.svc.cluster.local:9090
          query: |
            scalar(
              sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{namespace="exercises"}) / sum(machine_cpu_cores) * 100
            )
