apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: taas93/ping-pong:5135afdf-8695-4c6c-84ed-165ba0359628
          env:
            - name: PORT
              value: "3006"
