apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
        - name: pv-image
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: ping-pong
          image: taas93/ping-pong:6b525450-01ba-4574-8766-4db103ba204a
          env:
            - name: PORT
              value: "3006"
