apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: taas93/ping-pong:07e92ef5-9b30-4357-aeca-8fc6ecc6981b
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: ping-pong-cm
                  key: port
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: ping-pong-cm
                  key: database_host
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: ping-pong-cm
                  key: database_port
            - name: DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  name: ping-pong-cm
                  key: database_user
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: ping-pong-cm
                  key: database_name
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgress-secrets
                  key: DATABASE_URL
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgress-secrets
                  key: DATABASE_PASSWORD
