apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
        - name: pv-image
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: ping-pong
          image: taas93/ping-pong:93734fad-a88c-4c34-be20-2d3447f92c9c
          volumeMounts:
            - name: pv-image
              mountPath: /usr/local/bin/files
          env:
            - name: PORT
              value: "3006"
