apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: ping-pong-dep
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ping-pong
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause:
            duration: 30s
        - setWeight: 50
        - pause:
            duration: 30s
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: exercises/ping-pong
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /health
              port: 3006
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            httpGet:
              path: /health
              port: 3006
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: ping-pong-cm
                  key: port
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: ping-pong-cm
                  key: database_host
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: ping-pong-cm
                  key: database_port
            - name: DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  name: ping-pong-cm
                  key: database_user
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: ping-pong-cm
                  key: database_name
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgress-secrets
                  key: DATABASE_URL
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgress-secrets
                  key: DATABASE_PASSWORD
