apiVersion: v1
kind: Secret
metadata:
  name: postgress-secrets
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3Jlc0Bwb3N0Z3Jlcy1zdmM6NTQzMi9wb25ncw==
  DATABASE_PASSWORD: cG9zdGdyZXM=
  POSTGRES_DB: cG9uZ3M=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
