apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
  - namespace.yaml
  - pv
  - todo-backend
  - todo-app
  - ingress.yaml
# images:
#   - name: project/backend
#     newName: europe-north1-docker.pkg.dev/project/my-repo/todo-app
#   - name: project/frontend
#     newName: europe-north1-docker.pkg.dev/project/my-repository/todo-backend
