apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: exercises
  name: image-claim
spec:
  storageClassName: log-output-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
