apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: pv-image
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: create-file
          image: taas93/create-file:85444adf-1f77-4a82-b8de-5c29f137367b
          volumeMounts:
            - name: pv-image
              mountPath: /usr/local/bin/files
        - name: file-output
          image: taas93/file-output:c3f332a4-f60c-4b58-9334-7a2cf8659774
          volumeMounts:
            - name: pv-image
              mountPath: /usr/local/bin/files
          env:
            - name: PINGPONG_URL
              value: "http://ping-pong-svc:2345"
