[package]
name = "todo-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-cors = "0.7"
actix-web = "4.11"
anyhow = "1.0"
dotenvy = "0.15"
env_logger = "0.11"
log = "0.4"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
tracing = "0.1"