services:
  db: #Running DB for development
    image: postgres:17-bookworm
    environment:
      - POSTGRES_DB=todos
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  nats:
    image: nats:alpine
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
