apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      volumes:
        - name: config
          configMap:
            name: todo-backend-cm
      containers:
        - name: todo-backend
          image: taas93/todo-backend:4ef13a26-97e3-44bd-8319-db7fa7af6dc5
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-backend-cm
                  key: port
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: todo-backend-cm
                  key: host
            - name: CLIENT_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-backend-cm
                  key: client_url
