apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: taas93/todo-backend:c3993d76-ae6d-4563-bbe3-0cde7ba8b796
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-backend-cm
                  key: port
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: todo-backend-cm
                  key: host
            - name: CLIENT_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-backend-cm
                  key: client_url
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: todo-backend-cm
                  key: database_host
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-backend-cm
                  key: database_port
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: todo-backend-cm
                  key: database_name
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: todo-secrets
                  key: database_url
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: todo-secrets
                  key: database_user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-secrets
                  key: database_password
