apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-files
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: todo-app
          image: taas93/todo-app:95ae6192-5484-41ac-86ad-f05f341cc678
          volumeMounts:
            - name: shared-files
              mountPath: /app/public
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-app-cm
                  key: port
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: todo-app-cm
                  key: host
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-app-cm
                  key: api_url
