apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-files
          persistentVolumeClaim:
            claimName: image-claim
        - name: config
          configMap:
            name: todo-app-cm
      containers:
        - name: todo-app
          image: taas93/todo-app:417254b0-eb22-4ad5-8e7d-ee6b647ee06d
          volumeMounts:
            - name: shared-files
              mountPath: /usr/local/bin/static/images
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-app-cm
                  key: port
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: todo-app-cm
                  key: host
            - name: IMAGE_DIR
              valueFrom:
                configMapKeyRef:
                  name: todo-app-cm
                  key: image_dir
            - name: IMAGE_PATH
              valueFrom:
                configMapKeyRef:
                  name: todo-app-cm
                  key: image_path
            - name: IMAGE_API
              valueFrom:
                configMapKeyRef:
                  name: todo-app-cm
                  key: image_api
            - name: SCHEDULE_EXPRESSION
              valueFrom:
                configMapKeyRef:
                  name: todo-app-cm
                  key: schedule_expression
