apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-files
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: todo-app
          image: taas93/todo-app:1c2b5dff-44a4-42cb-85d3-1c21893f3f4b
          volumeMounts:
            - name: shared-files
              mountPath: /usr/local/bin/static/images
          env:
            - name: PORT
              value: "3003"
