apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: taas93/todo-app:97fb7abf-a481-451e-bc3e-3f4038e2d167
          env:
            - name: PORT
              value: "3003"
