apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-app-dep
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-files
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: todo-app
          image: project/todo-app
          volumeMounts:
            - name: shared-files
              mountPath: /app/public
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-app-cm
                  key: port
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: todo-app-cm
                  key: host
