[package]
name = "log-output"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6"
actix-web = "4.11"
dotenvy = "0.15"
env_logger = "0.11"
log = "0.4"
chrono = "0.4"
rand = "0.9"
uuid = { version = "1.16", features = ["v4", "fast-rng", "macro-diagnostics"]}