apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-controller-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-controller
  template:
    metadata:
      labels:
        app: dummy-controller
    spec:
      serviceAccountName: dummy-controller-account
      containers:
        - name: dummy-controller
          image: dummysite/controller
