apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- clusterrole.yaml
- clusterrolebinding.yaml
- serviceaccount.yaml
- resourcedefinition.yaml
- deployment.yaml

images:
- name: dummysite/controller
  newName: taas93/dummy-controller
  newTag: 180a8844-7334-4bfc-bc87-7dc263e62bba