apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-backend-cm
data:
  port: "3003"
  host: "0.0.0.0"
  client_url: "http://todo-app-svc:80"
  database_host: "postgres-svc"
  database_name: "todos"
  database_port: "5432"
  nats: "nats://my-nats:4222"
