apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dep
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: project/todo-backend
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 5
            httpGet:
              path: /health
              port: 3006
          resources:
            requests:
              cpu: "10m"
              memory: "50Mi"
            limits:
              cpu: "50m"
              memory: "100Mi"
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-backend-cm
                  key: port
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: todo-backend-cm
                  key: host
            - name: CLIENT_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-backend-cm
                  key: client_url
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: todo-backend-cm
                  key: database_host
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-backend-cm
                  key: database_port
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: todo-backend-cm
                  key: database_name
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: todo-secrets
                  key: database_url
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: todo-secrets
                  key: database_user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-secrets
                  key: database_password
