apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
type: Opaque
data:
  database_url: cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3Jlc0Bwb3N0Z3Jlcy1zdmM6NTQzMi9wb25ncw==
  database_user: cG9zdGdyZXM=
  database_password: cG9zdGdyZXM=
