name: Release application

on:
  push:
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  REGISTRY: europe-north1-docker.pkg.dev
  REPOSITORY: my-repo
  BRANCH: ${{ github.ref_name }}
  TODO_APP_IMAGE: todo-app
  TODO_APP_SERVICE: todo-app-dep
  TODO_BACKEND_IMAGE: todo-backend
  TODO_BACKEND_SERVICE: todo-backend-dep

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest
    environment: my-env

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ env.GKE_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - name: 'Use gcloud CLI'
        run: gcloud info

      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'

      - name: 'Set up Docker Buildx'
        run: gcloud auth configure-docker "$REGISTRY"

        # todo-app

      - name: 'Form the image name'
        run: echo "TODO_APP_IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$TODO_APP_IMAGE:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV

      - name: Build and Publish
        working-directory: the_project
        run: docker buildx build -t $TODO_APP_IMAGE_TAG --push ./todo-app

        # todo-backend

      - name: 'Form the image name'
        run: echo "TODO_BACKEND_IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$TODO_BACKEND_IMAGE:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV

      - name: Build and Publish
        working-directory: the_project
        run: docker buildx build -t $TODO_BACKEND_IMAGE_TAG --push ./todo-backend

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      - name: Deploy
        working-directory: the_project/manifests
        run: |-
          kustomize edit set image project/todo-app=$TODO_APP_IMAGE_TAG
          kustomize edit set image project/todo-backend=$TODO_BACKEND_IMAGE_TAG
          kustomize build . | kubectl apply -f -
          kubectl rollout status deployment $TODO_APP_SERVICE
          kubectl rollout status deployment $TODO_BACKEND_SERVICE
          kubectl get services -o wide
